### ISSUE TITLE
Error when trying to run locally

### ISSUE THREAD

**Issue by ashsinger** [starknet-io/starknet-website#353]
Hi,

I checked out the repo, followed the `README.md` , but after running`yarn dev` I get the following error:

```sh
[Error: ENOENT: no such file or directory, open '$HOME/starknet-website/_crowdin/data/redirects/en.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '$HOME/starknet-website/_crowdin/data/redirects/en.json'
}
```

Tried checking out `production` as well but same thing.

Any suggestions on how I might go about resolving the issue? I'm not sure if it has to do with my local setup or the branches are in a bad state.

**Comment by robwalsh21** [comment]
Hello @ashsinger, you can run yarn data which should fix this issue.

**Comment by ashsinger** [comment]
Yep, that fixed it :) 

Made a quick PR to add it to the `README.md`: https://github.com/starknet-io/starknet-website/pull/359
